services:
  - redis-server

setup_tasks:
 - mvn -B -q versions:display-dependency-updates
 - mvn -B -q clean install -DskipTests=true

tasks:
 - mvn license:check -Dlicense.header=COPYING-HEADER
 - mvn -B -q checkstyle:check
 - mvn -B -q pmd:check -Dpmd.printFailingErrors=true
 - mvn -B -q findbugs:check
 - mvn -B test
